import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import { Toaster } from "sonner";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // ajuste conforme necessário
  variable: '--font-poppins', // define como variável CSS
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
        <Toaster
          position="top-center"
          richColors
          theme="system"
          expand={false}
          closeButton
        />
      </body>
    </html>
  );
}
